@startuml packages_MyDiagram
set namespaceSeparator none
package "Project01" as Project01 {
}
package "Project01.aicashier" as Project01.aicashier {
}
package "Project01.aicashier.admin" as Project01.aicashier.admin {
}
package "Project01.aicashier.apps" as Project01.aicashier.apps {
}
package "Project01.aicashier.forms" as Project01.aicashier.forms {
}
package "Project01.aicashier.gemini_service" as Project01.aicashier.gemini_service {
}
package "Project01.aicashier.management" as Project01.aicashier.management {
}
package "Project01.aicashier.management.commands" as Project01.aicashier.management.commands {
}
package "Project01.aicashier.management.commands.init_rag" as Project01.aicashier.management.commands.init_rag {
}
package "Project01.aicashier.management.commands.sync_ai" as Project01.aicashier.management.commands.sync_ai {
}
package "Project01.aicashier.middleware" as Project01.aicashier.middleware {
}
package "Project01.aicashier.migrations" as Project01.aicashier.migrations {
}
package "Project01.aicashier.migrations.0001_initial" as Project01.aicashier.migrations.0001_initial {
}
package "Project01.aicashier.models" as Project01.aicashier.models {
}
package "Project01.aicashier.rag_service" as Project01.aicashier.rag_service {
}
package "Project01.aicashier.signals" as Project01.aicashier.signals {
}
package "Project01.aicashier.stripe_service" as Project01.aicashier.stripe_service {
}
package "Project01.aicashier.tests" as Project01.aicashier.tests {
}
package "Project01.aicashier.urls" as Project01.aicashier.urls {
}
package "Project01.aicashier.views" as Project01.aicashier.views {
}
package "Project01.config" as Project01.config {
}
package "Project01.config.asgi" as Project01.config.asgi {
}
package "Project01.config.settings" as Project01.config.settings {
}
package "Project01.config.urls" as Project01.config.urls {
}
package "Project01.config.wsgi" as Project01.config.wsgi {
}
package "Project01.fix_qr" as Project01.fix_qr {
}
package "Project01.manage" as Project01.manage {
}
package "Project01.seed_orders" as Project01.seed_orders {
}
package "Project01.seed_products" as Project01.seed_products {
}
package "Project01.setup_model" as Project01.setup_model {
}
package "Project01.test_full_payment" as Project01.test_full_payment {
}
package "Project01.test_omise_flow" as Project01.test_omise_flow {
}
package "Project01.test_optimizations" as Project01.test_optimizations {
}
package "Project01.test_payment_authenticated" as Project01.test_payment_authenticated {
}
package "Project01.test_payment_flow" as Project01.test_payment_flow {
}
package "Project01.test_payment_link" as Project01.test_payment_link {
}
package "Project01.theme" as Project01.theme {
}
package "Project01.theme.apps" as Project01.theme.apps {
}
Project01.aicashier.admin --> Project01.aicashier.models
Project01.aicashier.forms --> Project01.aicashier.models
Project01.aicashier.gemini_service --> Project01.aicashier.rag_service
Project01.aicashier.signals --> Project01.aicashier.models
Project01.aicashier.tests --> Project01.aicashier.models
Project01.aicashier.urls --> Project01.aicashier.views
Project01.aicashier.views --> Project01.aicashier.forms
Project01.aicashier.views --> Project01.aicashier.gemini_service
Project01.aicashier.views --> Project01.aicashier.models
Project01.aicashier.views --> Project01.aicashier.rag_service
Project01.seed_orders --> Project01.aicashier.models
Project01.seed_products --> Project01.aicashier.models
Project01.test_full_payment --> Project01.aicashier.models
Project01.test_optimizations --> Project01.aicashier.models
Project01.test_optimizations --> Project01.aicashier.rag_service
Project01.test_payment_authenticated --> Project01.aicashier.models
Project01.test_payment_flow --> Project01.aicashier.views
Project01.test_payment_link --> Project01.aicashier.models
Project01.test_payment_link --> Project01.aicashier.stripe_service
@enduml
