# Generated by Django 5.2.6 on 2025-12-10 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("promptpay", "PromptPay QR"),
                            ("cash", "เงินสด"),
                            ("card", "บัตรเครดิต"),
                            ("stripe", "Stripe Payment"),
                        ],
                        default="promptpay",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการชำระเงิน"),
                            ("confirmed", "ชำระเงินแล้ว"),
                            ("failed", "ชำระเงินล้มเหลว"),
                            ("expired", "หมดเวลา"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code_data",
                    models.TextField(
                        blank=True, help_text="QR Code payload for PromptPay", null=True
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        help_text="Unique payment reference", max_length=50, unique=True
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Checkout Session ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "stripe_payment_link_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Payment Link ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "stripe_payment_url",
                    models.TextField(
                        blank=True,
                        help_text="Stripe Payment Link or Checkout URL",
                        null=True,
                    ),
                ),
                (
                    "stripe_qr_code_url",
                    models.URLField(
                        blank=True,
                        help_text="Stripe QR Code URL",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "stripe_response",
                    models.JSONField(
                        blank=True, help_text="Full Stripe API response", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="QR expires after 15 minutes", null=True
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Bank transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        help_text="รหัสสินค้า เช่น P0001, F1234",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="อัพโหลดรูปภาพสินค้า",
                        null=True,
                        upload_to="products/",
                    ),
                ),
                (
                    "ai_information",
                    models.TextField(
                        blank=True,
                        help_text="ข้อมูลส่วนนี้จะถูกใช้โดย AI เพื่อให้ข้อมูลกับลูกค้า",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="aicashier.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="aicashier.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/Disable AI Sales Assistant"
                    ),
                ),
                (
                    "greeting_message",
                    models.TextField(
                        default="สวัสดีครับ! ยินดีต้อนรับสู่ร้าน AI CASHIER",
                        help_text="ข้อความทักทายเริ่มแรก",
                    ),
                ),
                (
                    "promotion_text",
                    models.TextField(
                        default="เรามีโปรโมชั่นพิเศษ: ซื้อ 2 แก้ว ลด 10%",
                        help_text="ข้อความแนะนำโปรโมชั่น",
                    ),
                ),
                (
                    "sales_steps",
                    models.TextField(
                        default="1. ทักทาย\n2. ถามความต้องการ\n3. แนะนำสินค้า\n4. ให้ดูรายละเอียด\n5. เสนอราคา\n6. ยืนยันการสั่งซื้อ\n7. ขอบคุณและลาจาก",
                        help_text="ลำดับขั้นตอนการขายให้ลูกค้า (แต่ละขั้นตอนคั่นด้วย newline)",
                    ),
                ),
                (
                    "closing_message",
                    models.TextField(
                        default="ขอบคุณที่ใช้บริการ! หวังว่าจะพบคุณอีกครั้ง",
                        help_text="คำลงท้ายหลังจากขายสินค้า",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "featured_item_1",
                    models.ForeignKey(
                        blank=True,
                        help_text="เมนูแรก (ด้านบน)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_as_first",
                        to="aicashier.product",
                    ),
                ),
                (
                    "featured_item_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="เมนูที่สอง (ด้านบน)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_as_second",
                        to="aicashier.product",
                    ),
                ),
                (
                    "featured_item_3",
                    models.ForeignKey(
                        blank=True,
                        help_text="เมนูที่สาม (ด้านบน)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_as_third",
                        to="aicashier.product",
                    ),
                ),
                (
                    "featured_item_4",
                    models.ForeignKey(
                        blank=True,
                        help_text="เมนูที่สี่ (ด้านบน)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_as_fourth",
                        to="aicashier.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Settings",
                "verbose_name_plural": "AI Settings",
            },
        ),
    ]
