# Generated by Django 5.2.6 on 2025-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="ชื่อโปรโมชั่น", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="รายละเอียดโปรโมชั่น", null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="อัพโหลดรูปภาพโปรโมชั่น",
                        null=True,
                        upload_to="promotions/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="เปิด/ปิดการแสดง"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="ลำดับการแสดง (เรียงจากน้อยไปมาก)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
