# Generated by Django 5.2.6 on 2025-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0002_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cashier", "พนักงานแคชเชียร์ (หน้าร้าน)"),
                    ("order_manager", "พนักงานจัดการออเดอร์ (คิวออเดอร์)"),
                ],
                help_text="สิทธิ์การใช้งานของพนักงาน",
                max_length=20,
                null=True,
            ),
        ),
    ]
