# Generated by Django 5.2.6 on 2025-12-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0003_customer_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, help_text="หมายเลขออเดอร์ (รีเซ็ททุกวัน)", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("online", "🌐 ออนไลน์"), ("counter", "🏪 หน้าร้าน")],
                default="online",
                help_text="ประเภทออเดอร์",
                max_length=20,
            ),
        ),
    ]
