# Generated by Django 5.2.6 on 2025-12-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0005_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
    ]
