# Generated by Django 5.2.6 on 2025-12-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0006_remove_product_quantity_from_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cashier", "พนักงานแคชเชียร์ (หน้าร้าน)"),
                    ("order_manager", "พนักงานจัดการออเดอร์ (คิวออเดอร์)"),
                    ("order_complete", "พนักงานยืนยันเสร็จ (ยืนยันคิว)"),
                ],
                help_text="สิทธิ์การใช้งานของพนักงาน",
                max_length=20,
                null=True,
            ),
        ),
    ]
