# Generated by Django 5.2.6 on 2026-01-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0007_add_order_complete_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="voice_commands",
            field=models.TextField(
                default="เพิ่ม|add\nลบ|remove\nเอาออก|delete\nลดจำนวน|decrease\nลด|reduce",
                help_text="คำสั่งเสียงสำหรับการเพิ่ม/ลบสินค้า (แต่ละคำคั่นด้วย newline เป็น 'คำภาษาไทย|คำภาษาอังกฤษ')",
            ),
        ),
    ]
