# Generated by Django 5.2.6 on 2026-01-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0008_aisettings_voice_commands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aisettings",
            name="voice_commands",
            field=models.TextField(
                default="[เพิ่ม] เพิ่ม|add|ใส่|สั่ง|ซื้อ\n[ลด] ลด|decrease|ลดลง|ลดจำนวน|reduce\n[ลบ] ลบ|delete|remove|เอาออก|ถอด|หยิบออก",
                help_text="คำสั่งเสียงจัดการสินค้า รูปแบบ: [ประเภท] คำไทย|คำอังกฤษ (ประเภท: เพิ่ม | ลด | ลบ)",
            ),
        ),
    ]
