# Generated by Django 5.2.6 on 2026-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0010_alter_aisettings_voice_commands"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aisettings",
            name="voice_commands",
        ),
        migrations.AddField(
            model_name="aisettings",
            name="voice_commands_add",
            field=models.TextField(
                default="เพิ่ม|add|ใส่|put|สั่ง|order|ซื้อ|buy",
                help_text="คำสั่งเสียงสำหรับ เพิ่มสินค้า (แต่ละคำคั่นด้วย |)",
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="voice_commands_decrease",
            field=models.TextField(
                default="ลด|decrease|ลดจำนวน|reduce|ลดลง|down",
                help_text="คำสั่งเสียงสำหรับ ลดจำนวนสินค้า (แต่ละคำคั่นด้วย |)",
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="voice_commands_delete",
            field=models.TextField(
                default="ลบ|delete|เอาออก|remove|หยิบออก|pick|ถอด|extract",
                help_text="คำสั่งเสียงสำหรับ ลบสินค้า (แต่ละคำคั่นด้วย |)",
            ),
        ),
    ]
