# Generated by Django 5.2.6 on 2026-02-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0011_remove_aisettings_voice_commands_and_more"),
    ]

    operations = []
