# Generated by Django 5.2.6 on 2026-02-15 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0012_fix_order_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_query", models.TextField(help_text="คำถาม/คำค้นหาของลูกค้า")),
                ("ai_response", models.TextField(help_text="คำตอบจาก AI")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Log",
                "verbose_name_plural": "Chat Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="aicashier_c_created_d7f936_idx"
                    ),
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="aicashier_c_custome_56cd6d_idx",
                    ),
                ],
            },
        ),
    ]
