# Generated by Django 5.2.6 on 2026-02-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aicashier", "0013_chatlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatLog",
        ),
    ]
